[package]
name = "web_project"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.0"
rocket_dyn_templates = { version = "0.2", features = ["tera"] }
serde = "1.0" 
sea-orm = { version = "1.1.7", features = ["sqlx-postgres", "runtime-tokio-rustls"] }